---
# The most valuable linters; they are required to pass for PR to be merged.

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # use "github.com/golang/protobuf/proto" instead
      - github.com/gogo/protobuf/proto
      # use github.com/percona-platform/dbaas-controller/k8s_api/api/core/v1 instead https://jira.percona.com/browse/PMM-6863
      - k8s.io/api/core/v1
      # use k8s.io/apimachinery/pkg/... instead https://jira.percona.com/browse/PMM-6863
      - k8s.io/apimachinery/pkg/api/resource
      - k8s.io/apimachinery/pkg/apis/meta/v1
      - k8s.io/apimachinery/pkg/apis/runtime
      - k8s.io/apimachinery/pkg/apis/types
      - k8s.io/apimachinery/pkg/apis/util/intstr

  goimports:
    local-prefixes: github.com/percona-platform/dbaas-controller

linters:
  disable-all: true
  enable:
    - depguard
    - goimports
    - govet
    - ineffassign
    - staticcheck

issues:
  exclude-use-default: false

run:
  skip-dirs:
    - k8s_api/apimachinery
    - k8s_api/api
