apiVersion: v1
kind: Pod
metadata:
  name: hello1
spec:
  containers:
  - name: sleep20-1
    image: alpine
    command: ['sh', '-c', 'sleep 10']
    resources:
      requests:
         cpu: 100m
         memory: 128M
  - name: sleep20-2
    image: alpine
    command: ['sh', '-c', 'sleep 10']
    resources:
      requests:
         cpu: 200m
         memory: 32M
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: hello2
spec:
  containers:
  - name: sleep20-1
    image: alpine
    command: ['sh', '-c', 'sleep 10']
    resources:
      requests:
         cpu: 60m
         memory: 16M
  restartPolicy: Never
