apiVersion: v1
kind: Pod
metadata:
  name: hello1
spec:
  containers:
  - name: sleep10-1
    image: alpine
    command: ['sh', '-c', 'sleep 10']
    resources:
      requests:
         cpu: 100m
         memory: 128M
  - name: sleep10-2
    image: alpine
    command: ['sh', '-c', 'sleep 10']
    resources:
      requests:
         cpu: 0.2
         memory: 32Mi
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: hello2
spec:
  containers:
  - name: sleep10-1
    image: alpine
    command: ['sh', '-c', 'sleep 10']
    resources:
      requests:
         cpu: 60m
         memory: 0.1Gi
  - name: sleep10-2
    image: alpine
    command: ['sh', '-c', 'sleep 10']
    resources:
      requests:
         cpu: 60m
         memory: 20000000
  - name: sleep10-3
    image: alpine
    command: ['sh', '-c', 'sleep 10']
  restartPolicy: Never
